services:
  cosnole-server-app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: console-server-app
    restart: always
    # ports:
      # - "5000:5000"
    networks:
      - network-console
    volumes:
      - uploads-data:/app/uploads
  
  # nginx
  nginx-container:
    image: nginx:1.27-alpine
    ports:
      - "5001:5001" # 将容器的5001端口映射到主机的5000端口
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # 挂载自定义的Nginx配置文件
    depends_on:
      - cosnole-server-app
    networks:
      - network-console


volumes:
  uploads-data:


networks:
  network-console:
    driver: bridge
