application:
  prefix: '/api'
  port: 5000

# ip转换为城市
ipToCityUrl: https://whois.pconline.com.cn/ipJson.jsp

# 数据库配置
db:
  mysql:
    host: '172.19.0.2' # 数据库地址
    username: 'root' # 数据库用户名
    password: '你的密码'
    database: 'console-server'
    port: 3306
    charset: 'utf8mb4' # 数据库编码
    logger: 'console' # 日志记录方式，支持 'file' 和 'console'
    logging: true # 是否开启日志记录
    multipleStatements: true # 是否允许执行多条SQL语句
    synchronize: false # 是否自动同步数据库表结构
    poolSize: 10 # 连接池大小
    connectorPackage: 'mysql2'   
    timezone: '+08:00' # 时区
    dateStrings: true # 是否将日期转换为字符串
    supportBigNumbers: true # 是否支持大数字
    bigNumberStrings: true # 是否将大数字转换为字符串

redis:
  host: '172.19.0.3' # 连接地址
  port: 6379
  password: '你的密码' # 密码(可以为空)

file:
  uploadDir: 'uploads' # 文件上传目录

# jwt 配置
jwt:
  secret: 'peng'
  expiresIn: '1h' # 有效期
  refreshExpiresIn: '7d' # 刷新有效期

